[package]
name = "wayggle-bg"
version = "0.1.0"
edition = "2024"
authors = ["Daisuke Matsunami (Comavius) <comavius@proton.me>"]
description = "Dynamically rendered wallpaper for Wayland powered by shader technology"

[dependencies]
# Graphics Libraries
khronos-egl = { version = "6.0.0", features = ["static"] }
glow = "0.16.0"
# Wayland protocol
wayland-client = "0.31.10"
wayland-protocols-wlr = { version = "0.3.8", features = ["client"] }
wayland-egl = "0.32.7"
# Application
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
clap = { version = "4.5.42", features = ["derive"] }
